[2067bc]
title="2067BC"
year=1992
tags="game,ex-commercial"
publisher="Oregan"
description="Prehistoric themed sideways scroller"
archive="2067bc.zip"
app-path="!2067BC"
best-cpu="arm250"
ff-ms=17000

[alerion]
title="Alerion"
year=1994
tags="game,ex-commercial"
publisher="Archimedes World"
author="Felix Andrew"
description="2D vertical scrolling shooter. This is the 1994 Arhcimedes World release of the original 1988 game."
archive="alerion.zip"
app-path="!Alerion"
ff-ms=17000

[alien-invasion]
title="Alien Invasion"
year=1994
tags="game,ex-commercial"
publisher="Archimedes World"
author="Adrian S. W. Nelson, G. Stanley"
description="Invaders remake with customisiable levels and graphics"
disc="http://acorn.revivalteam.de/Download/Images/Alien%20Invasion.zip"

[aliped]
title="Aliped"
year=1990
publisher="Alien Images"
tags="game,ex-commercial"
description="Medieval point-and-click adventure game"
disc="http://acorn.revivalteam.de/Download/Images/Aliped.zip"


[burnout]
title="Burn 'Out"
year="1995"
publisher="Oregan"
author="Ian Jeffray, David Flynn, Joe Nash"
tags="game,ex-commercial"
archive="http://ian.jeffray.co.uk/riscos/BurnOut/burn'out.zip"
best-cpu="arm3"
app-path="!Burn"
ff-ms=17000
description="Burn 'Out is a racing game like no other. Racing on a unique island through woodland, beaches and mountains on tracks that have more in common with rollercoaster rides than conventional racetracks, you must pit your skill and reflexes against nine other dune-buggy drivers and finish in the top three to continue to the next race. Choose from a selection of drivers and buggies and prepare for the ultimate arcade racing experience."
info-url="http://ian.jeffray.co.uk/riscos/BurnOut/"

[elite]
title="Elite"
tags="game,ex-commercial"
year=1995
archive="elite.zip"
author="Warren Burch, Clive Gringras"
description="The classic space trading game"
version="1.14"
app-path="!élite"
click-icon=true
ff-ms=20000
info-url="http://www.elitehomepage.org/arc/index.htm"

[swiv]
title="S.W.I.V."
tags="game,ex-commercial"
year=1992
publisher="Krysalis Software"
description="Fast-paced vertical 2D shooter"
disc="http://acorn.revivalteam.de/Download/Images/SWIV.zip"

[mr-doo]
title="Mr. Doo"
tags="game,ex-commercial"
year=1992
publisher="Image Systems"
archive="mr-doo.zip"
app-path="!MrDoo"
ff-ms=17000

[bughunter]
title="Bug Hunter"
tags="game,ex-commercial"
year=1990
publisher="Minerva Software"
author="Ian Richardson"
archive="bughunter.zip"
app-path="!BugHunter"
ff-ms=17000

# todo - need to !boot bughunter before loading moondash
# [moondash]
# title="Moon Dash"
# tags="game,ex-commercial"
# year=1990
# publisher="Minerva Software"
# author="Ian Richardson"
# archive="moondash.zip"
# app-path="!MoonDash"
# ff-ms=17000

[bughunter2]
title="Bug Hunter in Space"
tags="game,ex-commercial"
year=1990
publisher="Minerva Software"
author="Ian Richardson"
archive="bughunter-in-space.zip"
app-path="!BugHuntII"
ff-ms=17000

[hamsters]
title="Hamsters"
tags="game,ex-commercial"
version=1.10
year=1994
author="Tom Cooper"
best-cpu="arm250"
archive="http://arcarc.nl/archive/Games/H/Hamsters/Hamsters%20%2819xx%29%28Tom%20Cooper%29.zip"
app-path="!Hamsters"
click-icon=true
ff-ms=17000
description="""
Cartoon 2D platformer where you play a small furry creature with a large mallet which you must use to squish cute animals.
"""

[asylum]
title="Asylum"
tags="game,ex-commercial"
version="2.02"
year=2002
author="Andy Southgate"
description="""
Young Sigmund has a few problems. To help him resolve his mental
instability you must enter the surreal world of his inner mind and
shut down the malfunctioning brain cells which are causing him these problems.
"""
archive="http://asylum.acornarcade.com/files/asy202.zip"
app-path="AsyNu.!Asylum"
click-icon=true
ff-ms=18100
info-url="http://asylum.acornarcade.com/index.php"
best-cpu="arm250"

[oddball]
title="Oddball"
tags="game"
version="2.00"
archive="http://asylum.acornarcade.com/files/oddball.zip"
author="Andy Southgate"
year=1995
description="""
Oddball is a bat and ball game, but on a massive scale. Just move the bat and 
hit the ball around until it destroys all of the green blocks. Then do the same 
for the rest of the levels. One problem. If the ball falls off the world into 
the swirling Abyss, you've lost it for good. Lose all of the balls and you've 
lost a life! Lose all of your lives, and that's it...
"""
app-path="OddballFD.!OddBall"
click-icon=true
ff-ms=18100
best-cpu="arm250"

#[botkiller]
#title="Botkiller"
#tags="game,ex-commercial"
#archive="http://www.acorn-gaming.org.uk/Download/Arcade/BK.zip"
#publisher="Artex Software"
#year=1997

[chaos]
title="Spheres of Chaos"
tags="game,ex-commercial"
archive="chaos.zip"
author="Iain McLeod"
year=1993
description="Fast-moving psychadelic take the classic asteroids formula"
app-path="!Chaos"
ff-ms=17000
best-cpu="arm250"

[twinworld]
title="Twinworld"
year=1991
description="Fantasy platformer"
publisher="Ubisoft"
tags="game,ex-commercial"
archive="twinworld.zip"
app-path="!TwinWorld"
ff-ms=17000

[paradroid2000]
title="Paradroid 2000"
year=1993
publisher="Graftgold Creative Software"
tags="game,ex-commercial"
disc="http://acorn.revivalteam.de/Download/Images/Paradroid2000.zip"
app-path="!Paradroid"
ff-ms=36000
