[2067bc]
title="2067BC"
year=1992
tags="game,ex-commercial"
publisher="Oregan"
description="Prehistoric themed sideways scroller"
disc="http://acorn.revivalteam.de/Download/Images/2067BC.zip"

[elite]
title="Elite"
tags="game,ex-commercial"
year=1995
disc="http://acorn.revivalteam.de/Download/Images/Elite.zip"
author="Warren Burch, Clive Gringras"
description="The classic space trading game"
version="1.14"

[swiv]
title="S.W.I.V."
tags="game,ex-commercial"
year=1992
publisher="Krysalis Software"
description="Fast-paced vertical 2D shooter"
disc="http://acorn.revivalteam.de/Download/Images/SWIV.zip"
