# Software from Acorn

[arthur-welcome]
title="Arthur Welcome Disc"
year=1987
description="""
The Welcome disc provided with the original 1987 Archimedes which ran Arthur OS.
"""
best-os="arthur120"
publisher="Acorn"
tags="utility"
disc="https://www.4corn.co.uk/archive/archiology/osdiscs/arthur/Welcome.adf"

[riscos2-app1]
title='RISC OS 2 Application Disc 1'
publisher="Acorn"
disc="Apps RiscOS2 disc1.zip"
tags='utility'

[riscos2-app2]
title='RISC OS 2 Application Disc 2'
publisher="Acorn"
disc='Apps RiscOS2 disc2.zip'
tags='utility'

[riscos3-app1]
title="RISC OS 3 Applications disc 1"
year=1992
publisher="Acorn"
description="Extra tools and utilities released with RISC OS 3."
disc="http://arcarc.nl/archive/ROMS/OS/OS%20Support%20Discs/RISC%20OS%203.10/RISC%20OS%203.10%20Applications%20Disc%201%20%281992%29%28Acorn%20Computers%29.adf"
best-os="riscos311"
tags="utility"

[riscos3-app2]
title="RISC OS 3 Applications disc 2"
year=1992
publisher="Acorn"
description="Extra tools and utilities released with RISC OS 3."
disc="http://arcarc.nl/archive/ROMS/OS/OS%20Support%20Discs/RISC%20OS%203.10/RISC%20OS%203.10%20Applications%20Disc%202%20%281992%29%28Acorn%20Computers%29.adf"
best-os="riscos311"
tags="utility"

[riscos3-support]
title="RISC OS 3 Support disc"
year=1992
publisher="Acorn"
description="Extra tools and utilities released with RISC OS 3."
disc="http://arcarc.nl/archive/ROMS/OS/OS%20Support%20Discs/RISC%20OS%203.10/RISC%20OS%203.10%20Support%20Disc%20%281992%29%28Acorn%20Computers%29.adf"
best-os="riscos311"
tags="utility"