# Software from Acorn

[arthur-welcome]
title="Arthur Welcome Disc"
year=1987
description="""
The Welcome disc provided with the original 1987 Archimedes which ran Arthur OS.
"""
best-os="arthur120"
publisher="Acorn"
tags="utility"
disc="https://www.4corn.co.uk/archive/archiology/osdiscs/arthur/Welcome.adf"

[riscos2-app1]
title='RISC OS 2 Application Disc 1'
publisher="Acorn"
disc="Apps RiscOS2 disc1.zip"
tags='utility'

[riscos2-app2]
title='RISC OS 2 Application Disc 2'
publisher="Acorn"
disc='Apps RiscOS2 disc2.zip'
tags='utility'

[riscos3-app1]
title="RISC OS 3 Application disc 1"
year=1992
description="Extra tools and utilities released with RISC OS 3."
disc="https://www.4corn.co.uk/archive/archiology/osdiscs/riscos310/App1.adf"
best-os="riscos311"
tags="utility"