# Modern demoscene creations (i.e. post-90s!) 

[bs-tipsy-cube]
title="Tipsy Cube"
publisher="Bitshifters & Slipstream"
author="Kieran^Bitshifters, ToBach^Slipstream, Phoenix^Quantum"
year=2022
disc="https://bitshifters.github.io/content/bs-tipsy-cube.zip"
tags="demoscene"
info-url="https://bitshifters.github.io/posts/prods/bs-tipsy-cube.html"

[bs-django01]
title="Chipo Djano 01"
publisher="Rabenauge, Bitshifters & the great composers of the Amiga scene!"
author="Bodo, Insane, Krill/Plush, Leonard/Oxygene, Kieran/Bitshifters, Phoenix/Quantum, Titus, Virgill, Juice, Okeanos, Dalzey, Slash, Vedder, Curt Cool, Triance, Ma2e "
year=2022
disc="https://bitshifters.github.io/content/bs-django01.zip"
tags="demoscene,music"
info-url="https://bitshifters.github.io/posts/prods/bs-chipo-django1.html"


#https://bitshifters.github.io/content/bs-django01.zip
#https://bitshifters.github.io/content/bs-popular-demand.arc