# Modern demoscene creations (i.e. post-90s!) 

[bs-chequered-past]
title="Chequered Past"
publisher="Bitshifters & Torment"
author="Kieran^Bitshifters, Phoenix^Quantum, Rhino^Torment, Spiny^Torment"
year=2023
archive="bs-chequered-past.zip"
best-cpu="arm250"
app-path="!Chequered"
ff-ms=17000
sound-filter=2
tags="demoscene"
info-url="https://bitshifters.github.io/posts/prods/bs-chequered-past.html"

[bs-tipsy-cube]
title="Tipsy Cube"
publisher="Bitshifters & Slipstream"
author="Kieran^Bitshifters, ToBach^Slipstream, Phoenix^Quantum"
year=2022
archive="https://bitshifters.github.io/content/bs-tipsy-cube,ddc"
best-cpu="arm250"
app-path="!Tipsy"
ff-ms=16700
sound-filter=2
tags="demoscene"
info-url="https://bitshifters.github.io/posts/prods/bs-tipsy-cube.html"

[bs-django01]
title="Chipo Django 1"
publisher="Rabenauge, Bitshifters & the great composers of the Amiga scene!"
author="Bodo, Insane, Krill/Plush, Leonard/Oxygene, Kieran/Bitshifters, Phoenix/Quantum, Titus, Virgill, Juice, Okeanos, Dalzey, Slash, Vedder, Curt Cool, Triance, Ma2e "
year=2022
archive="https://bitshifters.github.io/content/bs-django01,ddc"
app-path="!Django01"
ff-ms=17000
sound-filter=2
tags="demoscene,music"
info-url="https://bitshifters.github.io/posts/prods/bs-chipo-django1.html"

[bs-django02]
title="Chipo Django 2"
publisher="Rabenauge, Bitshifters Collective"
year=2023
archive="https://bitshifters.github.io/content/bs-django02,ddc"
app-path="!Django02"
ff-ms=19000
sound-filter=2
tags="demoscene,music"
description="Released at Revision 2023, with tracks from Soda7, Slime, Maze, Triace, Okeanos, NE7, Tobach, Dalezy,Slash,Virgill Curt Cool, Punnik, Lord and 4mat."
info-url="https://www.pouet.net/prod.php?which=94151"

[bs-popular-demand]
title="Back by Popular Demand"
publisher="Bitshifters & Torment"
author="Kieran, Rhino, Spiny, Phoenix / Quantum"
year=2020  
archive="https://bitshifters.github.io/content/bs-popular-demand.arc"
app-path="!Demand"
ff-ms=15000
sound-filter=2
tags="demoscene"
info-url="https://bitshifters.github.io/posts/prods/bs-popular-demand.html"
best-cpu="arm250"

[bs-mikroreise]
title="Mikroreise"
publisher="Bitshifters & Torment"
author="Kieran^Bitshifters, Rhino^Torment, Spiny^Torment"
year=2023  
description="""
The Deadline demoparty in Berlin has a unique Three Dee competition in which participants 
are challenged to make the best demo production using Anaglyph 3D. This is a stereoscopic 
3D effect using red-cyan filtered glasses.

Mikroreise means Micro Journey (or Small Trip) in German, and was our humble entry for 
the compo. You will need some red-cyan glasses to see this demo in 3D!!
"""
archive="https://bitshifters.github.io/content/bs-mikroreise,ddc"
app-path="!Reise"
ff-ms=15000
sound-filter=2
tags="demoscene"
info-url="https://bitshifters.github.io/posts/prods/bs-mikroreise.html"
best-cpu="arm250"

[bs-push]
title="Push"
publisher="Bitshifters & Torment"
author="Kieran^Bitshifters, Rhino^Torment"
year=2024
description="""
A 64Kb demo for the Acorn Archimedes released at Revision 2024 in the Oldschool Demo compo. 
An experiment in real-time particle physics.
"""
archive="https://bitshifters.github.io/content/bs-push,ddc"
app-path="!Push"
ff-ms=15000
sound-filter=2
tags="demoscene"
info-url="https://bitshifters.github.io/posts/prods/bs-push.html"
best-cpu="arm250"

[bs-archieklang]
title="ArchieKlang Announcetro"
publisher="Bitshifters & Alcatraz & Torment"
author="Kieran^Bitshifters, Virgill^Alcatraz, Rhino^Torment "
year=2024
description="""
A cheeky 28kb intro for the Acorn Archimedes released at NOVA 2024 in the Oldschool Demo Compo. 
This is the first production on the Archimedes to use Virgill’s AmigaKlang soft synth -
it generates 280+kb of sample data from just a few kb of code!
"""
archive="https://bitshifters.github.io/content/bs-archieklang,ddc"
app-path="!AKlang"
ff-ms=20000
sound-filter=2
tags="demoscene"
info-url="https://bitshifters.github.io/posts/prods/bs-archieklang.html"
best-cpu="arm250"

[progen-dither]
title="I heard you like dithering"
author="Progen"
year=2023
archive="https://b-em.bbcmicro.com/dither.zip"
tags="demoscene"
app-path="!Dither"
best-cpu="arm3"
min-mem="4MB"
ff-ms=31500
info-url="https://stardot.org.uk/forums/viewtopic.php?f=29&t=26152"
description="4K intro - an experiment with truecolour type effects on VIDC"
sound-filter=2

[progen-signals]
title="Signals"
year=2022
author="Crazy Q, Kalms, Evil, Progen"
publisher="DHS"
archive="https://b-em.bbcmicro.com/signals_arc.zip"
tags="demoscene,music"
app-path="!Signals"
description="Atari STe music demo, ported to the Archimedes by Progen"
sound-filter=2
ff-ms=21000

[progen-bad-apple]
title="Bad Apple"
year=2021
author="Anira, Masayoshi Minoshima, Progen"
tags="demoscene,music"
app-path="!BadApple"
archive="https://b-em.bbcmicro.com/BadApple.zip"
sound-filter=2
description="Port of the modern classic to Archimedes by progen"
ff-ms=16000

[master-horizon]
title="Horizon"
year=2019
author="The Master, Inversephase, Deathmunk"
archive="HorizonFinal.zip"
tags="demoscene"
app-path="!Horizon"
sound-filter=2
best-cpu="arm250"
ff-ms=15000
info-url="https://stardot.org.uk/forums/viewtopic.php?f=64&t=17368"

[desire-async]
title="Asynchronous"
publisher="Desire"
archive="https://b-em.bbcmicro.com/dsr_async_-archive-.zip"
app-path="!Async"
tags="demoscene"
best-cpu="arm250"
year=2022
ff-ms=16000
sound-filter=2
description="1st place entry in NOVA 2022 oldskool demo competition."

[desire-fathom]
title="Fathom"
publisher="Desire"
archive="https://b-em.bbcmicro.com/dsr_fathom.zip"
app-path="!Fathom"
tags="demoscene"
best-cpu="arm3"
year=2024
ff-ms=16000
sound-filter=2
description="64k intro released at NOVA 2024"
