# Modern demoscene creations (i.e. post-90s!) 

[bs-tipsy-cube]
title="Tipsy Cube"
publisher="Bitshifters & Slipstream"
author="Kieran^Bitshifters, ToBach^Slipstream, Phoenix^Quantum"
year=2022
archive="https://bitshifters.github.io/content/bs-tipsy-cube,ddc"
best-cpu="arm250"
app-path="!Tipsy"
ff-ms=16700
sound-filter=2
tags="demoscene"
info-url="https://bitshifters.github.io/posts/prods/bs-tipsy-cube.html"

[bs-django01]
title="Chipo Djano 01"
publisher="Rabenauge, Bitshifters & the great composers of the Amiga scene!"
author="Bodo, Insane, Krill/Plush, Leonard/Oxygene, Kieran/Bitshifters, Phoenix/Quantum, Titus, Virgill, Juice, Okeanos, Dalzey, Slash, Vedder, Curt Cool, Triance, Ma2e "
year=2022
archive="https://bitshifters.github.io/content/bs-django01,ddc"
app-path="!Django01"
ff-ms=17000
sound-filter=2
tags="demoscene,music"
info-url="https://bitshifters.github.io/posts/prods/bs-chipo-django1.html"

[bs-popular-demand]
title="Back by Popular Demand"
publisher="Bitshifters & Torment"
author="Kieran, Rhino, Spiny, Phoenix / Quantum "
year=2020  
archive="https://bitshifters.github.io/content/bs-popular-demand.arc"
app-path="!Demand"
ff-ms=15000
sound-filter=2
tags="demoscene"
info-url="https://bitshifters.github.io/posts/prods/bs-popular-demand.html"
best-cpu="arm250"

[progen-dither]
title="I heard you like dithering"
author="Progen"
year=2023
archive="http://b-em.bbcmicro.com/dither.zip"
tags="demoscene"
app-path="!Dither"
best-cpu="arm3"
min-mem="4MB"
ff-ms=31500
info-url="https://stardot.org.uk/forums/viewtopic.php?f=29&t=26152"
description="4K intro - an experiment with truecolour type effects on VIDC"
sound-filter=2

[progen-signals]
title="Signals"
year=2022
author="Crazy Q, Kalms, Evil, Progen"
archive="http://b-em.bbcmicro.com/signals_arc.zip"
tags="demoscene,music"
app-path="!Signals"
description="Atari STe music demo, ported to the Archimedes by Progen"
sound-filter=2
ff-ms=21000

[master-horizon]
title="Horizon"
year=2019
author="The Master, Inversephase, Deathmunk"
archive="HorizonFinal.zip"
tags="demoscene"
app-path="!Horizon"
sound-filter=2
best-cpu="arm250"
ff-ms=15000
info-url="https://stardot.org.uk/forums/viewtopic.php?f=64&t=17368"
