# Modern demoscene creations (i.e. post-90s!) 

[bs-tipsy-cube]
title="Tipsy Cube"
publisher="Bitshifters & Slipstream"
author="Kieran^Bitshifters, ToBach^Slipstream, Phoenix^Quantum"
year=2022
archive="https://bitshifters.github.io/content/bs-tipsy-cube,ddc"
best-cpu="arm250"
app-path="!Tipsy"
ff-ms=16700
tags="demoscene"
info-url="https://bitshifters.github.io/posts/prods/bs-tipsy-cube.html"

[bs-django01]
title="Chipo Djano 01"
publisher="Rabenauge, Bitshifters & the great composers of the Amiga scene!"
author="Bodo, Insane, Krill/Plush, Leonard/Oxygene, Kieran/Bitshifters, Phoenix/Quantum, Titus, Virgill, Juice, Okeanos, Dalzey, Slash, Vedder, Curt Cool, Triance, Ma2e "
year=2022
archive="https://bitshifters.github.io/content/bs-django01,ddc"
app-path="!Django01"
ff-ms=17000
tags="demoscene,music"
info-url="https://bitshifters.github.io/posts/prods/bs-chipo-django1.html"

[bs-popular-demand]
title="Back by Popular Demand"
publisher="Bitshifters & Torment"
author="Kieran, Rhino, Spiny, Phoenix / Quantum "
year=2020  
archive="https://bitshifters.github.io/content/bs-popular-demand.arc"
app-path="!Demand"
ff-ms=15000
tags="demoscene"
info-url="https://bitshifters.github.io/posts/prods/bs-popular-demand.html"
best-cpu="arm250"