[3dtanks]
tags="game,public-domain"
title="3D Tanks"
disc="3D_Tanks.zip"
author="Stuart Cupit and Simon Cruise"
year=1989

[bloxed]
tags="game,public-domain"
disc="bloxed.zip"
title="Bloxed"
description="Fun Tetris clone"
year=1995
author="Steven Singer"
