[3dtanks]
tags="game,public-domain"
title="3D Tanks"
disc="http://acorn.revivalteam.de/Download/Images/3D_Tanks.zip"
author="Stuart Cupit and Simon Cruise"
year=1989
description="Tron-style 3D tank battle"

[bloxed]
tags="game,public-domain"
archive="bloxed.zip"
title="Bloxed"
description="Fun Tetris clone"
app-path="!Bloxed"
ff-ms=17000
year=1995
author="Steven Singer"

[dinosaw]
title="DinoSaw"
tags="game,public-domain"
year=1993
author="Tom Cooper, Mark Smith"
disc="http://acorn.revivalteam.de/Download/Images/GameDemos03.zip"
description="""It's a prehistoric platformer... either jump over nasty things or hack 'em to death with yer chainsaw. 
You can tell when yer hurting something cos it bleeds! Nice huh?"""

[moonquake]
title="Moonquake"
tags="game,public-domain"
year=1992
author="Paul Taylor"
archive="http://arcarc.nl/archive/Games/M/Moon%20Quake%20%28FR%29/Moon%20Quake%20%28FR%29%20%281992%29%28Paul%20Taylor%29.zip"
description="Great bomberman clone"
app-path="!Moonquake"
ff-ms=17000