# Game demos

[lander]
title="Lander"
author="David Braben"
year=1989
disc="http://acorn.revivalteam.de/Download/Images/Lander.zip"
app-path="!Lander"
ff-ms=17000
mouse-capture="force" # prevent ship from exploding while moving mouse onto canvas
tags="game,demo"
description="The first-ever game written and released for the Archimedes"

[lemmings-demo]
title="Lemmings (Demo)"
publisher="Krisalis Software"
description="5 demo levels from the classic puzzle game. Save the Lemmings!"
year=1991
app-path="!LemDemo"
archive="lemdemo.zip"
tags="game,demo"
ff-ms=18100

[ohno-lemmings-demo]
title="Oh No! More Lemmings (Demo)"
publisher="Krisalis Software"
description="5 demo levels from the Lemmings extra levels pack."
year=1991
app-path="!OhnoLemdm"
archive="ohnolemdemo.zip"
tags="game,demo"
ff-ms=18100

[fervour-demo]
title="Fervour (Demo)"
year=1992
publisher="Clares"
author="Andrew Hersee"
archive="fervour-demo.zip"
app-path="!FervDemo"
click-icon=true
ff-ms=18100
tags="game,demo"

[nebulus-demo]
title="Nebulus (Demo)"
year=1992
publisher="Krisalis Software"
archive="nebulus-demo.zip"
app-path="!Nebulus"
tags="game,demo"
ff-ms=17000

[jamespond-demo]
title="James Pond (Demo)"
year=1992
publisher="Krisalis Software"
tags="game,demo"
archive="jamespond-demo.zip"
app-path="!JamesPond"
ff-ms=17000

[cataclysm-demo]
title="Cataclysm (Demo)"
year=1991
publisher="4th Dimension"
description="Water simulation puzzle game"
archive="cataclysm-demo.zip"
app-path="!CtclysD"
ff-ms=17000
tags="game,demo"

[chocksaway-demo]
title="Chocks Away (Demo)"
year=1991
publisher="4th Dimension"
author="Andrew Hutchings"
archive="chocksaway-demo.zip"
app-path="!Chocks_2"
ff-ms=20000
tags="game,demo"
best-cpu="arm3"

[quark-demo]
title="Quark (Demo)"
year=1993
publisher="Oregan Software"
author="The Zygotics"
archive="quark-demo.zip"
app-path="!"
ff-ms=15000
tags="game,demo"

[technodream-demo]
title="TechnoDream (Demo)"
publisher="Superior Software"
author="Graeme Richardson"
year=1993
archive="technodream-demo.zip"
app-path="!TechDream"
ff-ms=17000
tags="game,demo"
description="Side scrolling shoot-em-up sequel to Nevryon"

[flashback-demo]
title="Flashback"
year=1994
archive="flashback-demo.zip"
app-path="!Flashdemo"
ff-ms=17000
tags="game,demo"
author="Delphine Software, Dave Lawrence"
publisher="U.S. Gold"
best-cpu="arm250"