# Game demos

[lander]
title="Lander"
author="David Braben"
year=1989
disc="http://acorn.revivalteam.de/Download/Images/Lander.zip"
app-path="!Lander"
ff-ms=17000
tags="game,demo"

[lemmings-demo]
title="Lemmings (Demo)"
publisher="Krisalis Software"
description="5 demo levels from the classic puzzle game. Save the Lemmings!"
year=1991
app-path="!LemDemo"
archive="lemdemo.zip"
tags="game,demo"
ff-ms=18000

[ohno-lemmings-demo]
title="Oh No! More Lemmings (Demo)"
publisher="Krisalis Software"
description="5 demo levels from the Lemmings extra levels pack."
year=1991
app-path="!OhnoLemdm"
archive="ohnolemdemo.zip"
tags="game,demo"
ff-ms=18000

[fervour-demo]
title="Fervour (Demo)"
year=1992
publisher="Clares"
author="Andrew Hersee"
disc="http://acorn.revivalteam.de/Download/Images/GameDemos17.zip"
app-path="Fervour.!FervDemo"
tags="game,demo"

[nebulus-demo]
title="Nebulus (Demo)"
year=1992
publisher="Krisalis Software"
disc="http://acorn.revivalteam.de/Download/Images/GameDemos17.zip"
app-path="Nebulus.!Nebulus"
tags="game,demo"

[jamespond-demo]
title="James Pond (Demo)"
year=1992
publisher="Krisalis Software"
tags="game,demo"
disc="http://acorn.revivalteam.de/Download/Images/GameDemos13.zip"

[cataclysm-demo]
title="Cataclysm (Demo)"
year=1991
publisher="4th Dimension"
description="Water simulation puzzle game"
disc="http://acorn.revivalteam.de/Download/Images/GameDemos13.zip"
tags="game,demo"