# Game demos

[lander]
title="Lander"
author="David Braben"
year=1989
disc="http://acorn.revivalteam.de/Download/Images/Lander.zip"
app-path="!Lander"
ff-ms=17000
mouse-capture="force" # prevent ship from exploding while moving mouse onto canvas
tags="game,demo"
description="The first-ever game written and released for the Archimedes"

[lemmings-demo]
title="Lemmings (Demo)"
publisher="Krisalis Software"
description="5 demo levels from the classic puzzle game. Save the Lemmings!"
year=1991
app-path="!LemDemo"
archive="lemdemo.zip"
tags="game,demo"
ff-ms=18100

[ohno-lemmings-demo]
title="Oh No! More Lemmings (Demo)"
publisher="Krisalis Software"
description="5 demo levels from the Lemmings extra levels pack."
year=1991
app-path="!OhnoLemdm"
archive="ohnolemdemo.zip"
tags="game,demo"
ff-ms=18100

[fervour-demo]
title="Fervour (Demo)"
year=1992
publisher="Clares"
author="Andrew Hersee"
archive="fervour-demo.zip"
app-path="!FervDemo"
click-icon=true
ff-ms=18100
tags="game,demo"

[nebulus-demo]
title="Nebulus (Demo)"
year=1992
publisher="Krisalis Software"
archive="nebulus-demo.zip"
app-path="!Nebulus"
tags="game,demo"
ff-ms=17000

[jamespond-demo]
title="James Pond (Demo)"
year=1992
publisher="Krisalis Software"
tags="game,demo"
archive="jamespond-demo.zip"
app-path="!JamesPond"
ff-ms=17000

[cataclysm-demo]
title="Cataclysm (Demo)"
year=1991
publisher="4th Dimension"
description="Water simulation puzzle game"
archive="cataclysm-demo.zip"
app-path="!CtclysD"
ff-ms=17000
tags="game,demo"